sudo: required
dist: trusty
env:
  global:
  - secure: lnFpGFMbs+cLx7xwvcjtygxq4zeLYun2/TX/SR/+y+iBYFEefS+DKv+2kZ2qap4XRqtuRFpLWy5SzzH5eObHN8ftFkOTmdc60FI8dM8jYR6HChdkngxkKYx/PdkeY24fU8prt7owk8Fs1DwdVdhpVMvitpd3d+jpGF57pcJLCRE9/+DBSuSzYYvNC6Mz7M161MOKrr9OHu9VbSE4o5UiYEG/BhNvZsVVw1UOusZagjrNRIwCRA4ahvuW9Ie6MSsz/fSblgoxnEILpZKNY7sguGVAyZRpBofJku3FBHUajBKLZN3dEj7lEZFkuFBTAUud1PFenwBWKoQhzCQFKYsN8gdLDf4g8mTnhagJkdSk+IfKGU08TtnI6iGN7yoT2MksHonMDKStyot+urTqcluE5ih8a56hQKmNF3XBcDHanwa+bbYidsCc5T73UaogLKwZqkPKN+4PZuPfkKT8ycM9Y1jKU5bbjuGWlacbxiKZ9O3cUfhG71dLPVugtHODNChpf59VyEc6bVnR5UvFAKV1mzH9vZTWwJgBEZEvwTFg+2Dva8JFETF8ykGuXqArFRsmd6IfcOXQZolx/rP4WzC9qDlzC4kG4FVSgtAu3H6rvCiAWfXmjsH7Il8HHisYacPdDBKGVCsmrGplCQr0BxEe2fgD91Ii+rapgRNwpo1CxMs=
  - secure: dOpxk9aNFm2CyDqSTQIHfgJ7fX3q8Jd514kxMRT2GXJbn/x9Z1zHAkW+Br+YPwLU2r0B3GfWNZmYK3b5aS2xzob9infxyma9a/f5si+mc5CLlIVfv4BseYtW3xLNoNcuawSUHdRuACWqoa11hrTSh0xDj72jseX0JduAe8HvoM5U0cSLX6PHAIgOAzEg3emOkFnhr3184w8lm4JK9IsVR9MwE0cIUQMrCOHPCAJYvwYARmI3BDrUoKQe91REsy/jr7+TStzyoZKdxf34Mtd7JjjCG082vNUIS9L5pz1I6+QAeUgxYNwp6Vce0G7rXUscY8/sN5qx4OskXuZ18aYFnzaxblDbeDCLBPutGcuNXU+VHZyWttJY5jO6JPeIM73nzpPAxLcw6ajht4SIOI4qComJ+Kww6nb47fkA+YE4jfhCOXHr9POydrTxZTv3Q3T7ZUtOEbuztFsTl0qf+JvpTTibjqiS2phrt5nBYR2xQBHyJXCBLjfUewfu7Pdxf4r8GIuYA62WPINp/h54RLoG5vOJ/i4C/CutjJkxtQ4yrPmY2lLQhjmZ68EnBCe8EvMJZQFQV8FAHVl2AA9tqIKbseid+w/KbiyEEdRAsuBOATsB96u0WfVyc7C24TUbYhomERHuXOJlZAWTm8Jlac00PP29Wgdyf1/aXC+YiP0fM6A=
  - secure: RG3x8IGddIF6Oe8RqEzR5zO/VX9H24g2kO67jiPSyNe55Ni5BzR75yFZF7pcKQ4bHU2GQ6NeIQrDKqC3pwq1uiVnBakGJ7oANZPT8ifgns+RP+wS5MnBUFodyGubOFMllpoRTMWJUWjcS+V036WWg8xDvFm7kCifIZUnvR6R6nHYkSLuR9Zt5hGO8vE1qANGe5ulpJ3MPk+DFyefjhgP4zqxsTlUXjQ3TPDviSj9QX5wx8qXeIOrh3E87dRZKH1ILscY5KVXIb8IY3vd3PNySQY+kFppmOukhfBueM39UwX0mWo53cCq/E/lANRfiSxIvk73sRX1cdv5LwUgWqPrmGRm7rYXlzB64YpiaKW6M+btdd36TjSbr1H0xd4rVr0ltV1VEBAMzOtMNv4BG4XudoQHwGT0nG6MWi8lcLCgzxlEHbHkoCeQqUhkt1+TAGv9e2MIIqhmoL4m38i48eIvbhER/5NJGXEpsG2gwVAGF7wpF36IQKhHsUsvLWsotIEUIifwEyXTHbz9xiT9/XqPe48zW9autKWBsJ/Nbcj7ppQsYKdii2yjrrcEAP+gxkMYcEskKCZsqY6pBDytsvcKwAFUAgTaclR0JY3Qd6fxE1NWGsJK2ampYVSH+E607nGH0qwj5ok1yK/MyMBUMK8uFFmrLGQXYBrDeubtVLMNzo0=
  - secure: Q0jDZbztjS/MfkjdFxa336Hu5P9SuWycnLonrdBnOUa16NRRW+EULx6AA5pBxVQBVnEc++mFQR8fV95gI3BQ9FZNF5EKs941Ci/qzOGMRQKagqankX68yfFv8/HGKM45sTXIzq8v3kzHvI3X1hhr1hEvopTGFACMuTdJXJkEMI4a0kPV+H2bRWxjB3Ac0NMuKWRLbekAYBv8MU6NPNqdQvwT9rz49gR/IBCXyrJTRWkixRGIn1ff5GbkFtvu2ccLpHQLQVUf5+z1wKF6vPY+km1Y3KYvXPQ7j81nOoz+QhsJqJ1OgOIevd9ng97RkcQnmSS4p2496LTS+HkjwRw+ksBMJ7mVbZ+LMi6WkljSCrhzOKV5krr2rW38LXiQJ+zi455Eda7GoRqI7IOLpIsLuJ295Rnr+Li5kRE1lWtYdPiaL0AI098o//EPiNQqKy9RW5DIjK254NMiDcqMvAxQfUiqnZSlo01xlksWTVRmnldBqIIlLAi4CsBvygsY299UkHO7hvkwFuFM49Tbug1X9rjiiiHpfiOaKYp+hLoHVXokxspBCfutOTJSFPQdNeuT1Pzh1+BmgKtzIMLM4mKgcVIzddpKsgqsbSI5JRc/jXa8JlPsOrtg9cfk7lp2ApS+ajvVnVNRDeek2M+BxG5lbYUBN4ri33UKmsTuFkLsyhM=
language: java
jdk:
- oraclejdk8
before_install:
- bash .travis/deploy-codesigning.sh
install:
- mvn -N io.takari:maven:wrapper -Dmaven=3.5.0
- java -version && javac -version && ./mvnw -version -B
before_script:
- ./mvnw dependency:go-offline -B
script:
- ./mvnw clean install -B
deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
cache:
  directories:
  - $HOME/.m2
  - $HOME/.victims
